### ISSUE TITLE
esptool stops writing at different address

### ISSUE THREAD

**Issue by dkuku** [themadinventor/esptool#16]
Yesterday I tried to compile nodemcu with esp-open-sdk and everything went well, but I'm stuck when sending binaries to the module - no difference if I'm sending my binaries or the one from github. Tried on newest esptool.py. Trying to do it on raspberry pi (it has 3.3V and serial output) Previously I had no problems with the upload but I deleted the old version (around 3 jan). The strange thing is that it stops always at different address.  
```
pi@raspberrypi ~ $ python esptool.py -p /dev/ttyAMA0 write_flash 0x000000 nodemcu_latest.bin 
Connecting...
Erasing flash...
Writing at 0x00000300... (0 %) 
Traceback (most recent call last):
  File "esptool.py", line 456, in <module>
    esp.flash_block(block, seq)
  File "esptool.py", line 197, in flash_block
    struct.pack('<IIII', len(data), seq, 0, 0)+data, ESPROM.checksum(data))[1] != "\0\0":
  File "esptool.py", line 108, in command
    raise Exception('Invalid head of packet')
Exception: Invalid head of packet
pi@raspberrypi ~ $ python esptool.py -p /dev/ttyAMA0 write_flash 0x000000 nodemcu_latest.bin 
Connecting...
Erasing flash...
Writing at 0x00000000... (0 %)
Traceback (most recent call last):
  File "esptool.py", line 456, in <module>
    esp.flash_block(block, seq)
  File "esptool.py", line 197, in flash_block
    struct.pack('<IIII', len(data), seq, 0, 0)+data, ESPROM.checksum(data))[1] != "\0\0":
  File "esptool.py", line 108, in command
    raise Exception('Invalid head of packet')
Exception: Invalid head of packet
pi@raspberrypi ~ $ python esptool.py -p /dev/ttyAMA0 write_flash 0x000000 nodemcu_latest.bin 
Connecting...
Erasing flash...
Writing at 0x00000500... (0 %) 
Traceback (most recent call last):
  File "esptool.py", line 456, in <module>
    esp.flash_block(block, seq)
  File "esptool.py", line 197, in flash_block
    struct.pack('<IIII', len(data), seq, 0, 0)+data, ESPROM.checksum(data))[1] != "\0\0":
  File "esptool.py", line 108, in command
    raise Exception('Invalid head of packet')
Exception: Invalid head of packet
```

**Comment by dkuku** [comment]
NVM - I found out that the pullup resistor wasn't connected - please close this issue
