### ISSUE TITLE
ESP8266 firmware update problem 

### ISSUE THREAD

**Issue by mohamed1hateb** [themadinventor/esptool#94]
I have been trying to update the firmware using this  ESP8266_flasher_V00170901_00_
but no luck.

Error 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM11': WindowsError(5, 'Access is denied.')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM11': WindowsError(5, 'Access is denied.')

**Comment by projectgus** [comment]
Sorry, but `esp8266_flasher.py` is not this program - esptool.py is different. You'll need to talk to whoever you got this software from.

(Even though it's a different program, I'd suggest that you might need to right-click on the program and Run As Administrator in order to get permissions to access the COM port. Hope you get it sorted!)
